/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const RouterLink: typeof import('vue-router/auto')['RouterLink']
  const defineLoader: typeof import('vue-router/auto')['defineLoader']
  const definePage: typeof import('unplugin-vue-router/runtime')['_definePage']
  const onBeforeRouteLeave: typeof import('vue-router/auto')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router/auto')['onBeforeRouteUpdate']
  const useLink: typeof import('vue-router/auto')['useLink']
  const useRoute: typeof import('vue-router/auto')['useRoute']
  const useRouter: typeof import('vue-router/auto')['useRouter']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly RouterLink: UnwrapRef<typeof import('vue-router/auto')['RouterLink']>
    readonly defineLoader: UnwrapRef<typeof import('vue-router/auto')['defineLoader']>
    readonly definePage: UnwrapRef<typeof import('unplugin-vue-router/runtime')['_definePage']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router/auto')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router/auto')['onBeforeRouteUpdate']>
    readonly useLink: UnwrapRef<typeof import('vue-router/auto')['useLink']>
    readonly useRoute: UnwrapRef<typeof import('vue-router/auto')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router/auto')['useRouter']>
  }
}
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    readonly RouterLink: UnwrapRef<typeof import('vue-router/auto')['RouterLink']>
    readonly defineLoader: UnwrapRef<typeof import('vue-router/auto')['defineLoader']>
    readonly definePage: UnwrapRef<typeof import('unplugin-vue-router/runtime')['_definePage']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router/auto')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router/auto')['onBeforeRouteUpdate']>
    readonly useLink: UnwrapRef<typeof import('vue-router/auto')['useLink']>
    readonly useRoute: UnwrapRef<typeof import('vue-router/auto')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router/auto')['useRouter']>
  }
}
